name: Windows Compile

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        config: [Release, Debug]
        toolchain: [v143, clangcl]
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cmake -S . -B "build/x64" -G "Visual Studio 17 2022" -T ${{ matrix.toolchain }} -A x64 -DCMAKE_BUILD_TYPE:STRING=${{ matrix.config }}
          cmake --build ./build/x64
      - name: Publish packaged artifacts
        uses: actions/upload-artifact@v4
        with:
          name: prism-windows-x64
          path: build/x64/Debug/prism.exe
      - name: Test
        continue-on-error: true
        run: |
          cd build/x64
          ctest -j -C Debug
      - name: Echo Test Results
        run: cat build/x64/Testing/Temporary/LastTest.log